title: Law Awareness Weeks @ CDC
url: ""
favicon: /images/favicon.png
colors:
  primary-color: "#ee4f13"
  secondary-color: "#b81211"
  media-colors:
    - title: media-color-one
      color: "#ee5012"
    - title: media-color-two
      color: "#f8703b"
    - title: media-color-three
      color: "#f0794a"
    - title: media-color-four
      color: "#f4a282"
    - title: media-color-five
      color: "#eba286"
resources_name: Resources
description: This is an informational site about Law Awareness Weeks @ CDC.
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://pa-law-staging.netlify.app
prod: https://pa-law-prod.netlify.app
is_government: true
